schema = 3

[mod]
  [mod."github.com/adrg/xdg"]
    version = "v0.5.3"
    hash = "sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.5"
    hash = "sha256-UX9FajFqZApVFED3MYcq167iPwztnIck25ehfcOeFD8="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.2.1"
    hash = "sha256-oOi39n1MMETVl9ZKCODhlmFe0f/znEgxI3nJOW8yy2o="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.2"
    hash = "sha256-rTSqYEPooi8Uu4aXMW6k9dynOV+URYTGzVmbG3EQ7uo="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.27.6"
    hash = "sha256-u4yUgMwphs/7iwkhWrLgsHZru1InycgvY2ZmuxHQeLI="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20240521201337-686a1a2994c1"
    hash = "sha256-CsyN59w6sKERDI5kkdpq0YKmqdixyCHuN4FYE/56/BQ="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
