name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v29
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: build goshrt server
        run: |
          nix develop --command \
            go build cmd/goshrt/*.go
      - name: build goshrtc client
        run: |
          nix develop --command \
            go build cmd/goshrtc/*.go
