name: "Update flake lockfile"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * 5'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Run gomod2nix generate
        run: |
          nix develop --command \
            gomod2nix generate
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          token: ${{ secrets.GH_TOKEN_FOR_FLAKE_UPDATE }}
          pr-title: "Update flake.lock" 
          pr-labels: |
            nix
            automated
