name: lint

permissions: {}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          args: --timeout 15m -v
          install-mode: "goinstall"
