name: lint

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v26
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Lint
        run: |
          nix develop --command \
            golangci-lint run -v
      # - name: Install Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version-file: "go.mod"
      #     cache: false
      # - name: Lint
      #   uses: golangci/golangci-lint-action@v3.7.0
      #   with:
      #     version: latest
      #     args: --timeout 5m -v
      #     install-mode: "goinstall"
