name: nix ci
on: [push, pull_request]
jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: nix build goshrt
        run: |
          nix build .#goshrt
      - name: nix build goshrtc
        run: |
          nix build .#goshrtc
      - name: nix module
        run: |
          nix build .#nixosConfigurations.container.config.system.build.toplevel
      - name: nix flake check
        run: |
          nix flake check --no-build
