name: vuln
permissions: {}
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 5 * * 3"
  workflow_call:
jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Run govulncheck
        run: |
          nix develop --command \
            govulncheck -test ./...
